import ProjectCardProps from '../models/ProjectCardProps'

export const projects: ProjectCardProps[] = [
  {
    id: 1,
    title: 'Dewedd',
    thumbnail: '/dewedd.png',
    alternativeText: 'Dewedd mockup',
    description: 'MVP para Dewedd. Un planificador de bodas con funcionalidades y herramientas innovadoras.',
    categories: ['Full-stack'],
    technologies: ['React', 'Flask', 'Tailwind CSS'],
    url: 'https://dewedd.com',
    date: '2023',
  },
  {
    id: 2,
    title: 'Landing page Hotel Sur',
    thumbnail: '/hotel-sur.png',
    alternativeText: 'Hotel Sur mockup',
    description: 'Landing page para la banda de art-rock Hotel Sur. Diseño y desarrollo de la página.',
    categories: ['Front-end'],
    technologies: ['Astro'],
    url: 'https://hotelsur.es',
    date: '2023',
  },
  {
    id: 3,
    title: 'Creador de riders técnicos',
    thumbnail: '/riders.png',
    alternativeText: 'Riders mockup',
    description: 'Creador de riders técnicos para artistas, promotores y técnicos de sonido.',
    categories: ['Full-stack'],
    technologies: ['React', 'Flask', 'Tailwind CSS', 'PostgreSQL'],
    url: 'https://rider-creation-app.onrender.com/',
    date: '2023',
  },
  {
    id: 4,
    title: 'CES Técnicas del Agua / Higiene Industrial',
    thumbnail: '/ces.png',
    alternativeText: 'CES mockup',
    description:
      'Desarrollo de la página web, tienda y áreas de cliente de la empresa CES Técnicas del Agua en sus distintas vertientes.',
    categories: ['Full-stack'],
    technologies: ['PHP', 'WordPress', 'WooCommerce'],
    url: 'https://tecnicasdelaguaces.es/',
    date: '2023',
  },
  {
    id: 5,
    title: 'Creador de moodboards',
    thumbnail: '/moodboard.png',
    alternativeText: 'Moodboard mockup',
    description: 'Desarrollo de un creador de moodboards para diseñadores y creativos.',
    categories: ['Front-end'],
    technologies: ['React', 'Next.js', 'Tailwind CSS'],
    url: 'https://moodboard-app.vercel.app/',
    date: '2023',
  },
]
